# Generated by Django 5.1.7 on 2025-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapprest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
