# Generated by Django 5.1.7 on 2025-05-14 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_openspace_status'),
        ('myapprest', '0003_customuser_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='ward_executive_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('open_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.openspace')),
            ],
        ),
    ]
