# Generated by Django 5.1.7 on 2025-05-15 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0004_openspacebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openspacebooking',
            name='datetime',
        ),
        migrations.AddField(
            model_name='openspacebooking',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='openspacebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_space_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openspacebooking',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
