# Generated by Django 5.1.7 on 2025-05-15 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0005_remove_openspacebooking_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openspacebooking',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='openspacebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_space_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
