# Generated by Django 5.1.7 on 2025-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0006_remove_openspacebooking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openspacebooking',
            name='open_space',
        ),
        migrations.RemoveField(
            model_name='openspacebooking',
            name='user',
        ),
        migrations.AlterField(
            model_name='openspacebooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openspacebooking',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bookings/files/'),
        ),
        migrations.AlterField(
            model_name='openspacebooking',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
