# Generated by Django 5.1.7 on 2025-05-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_openspace_status'),
        ('myapprest', '0007_remove_openspacebooking_open_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspacebooking',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.openspace'),
            preserve_default=False,
        ),
    ]
