# Generated by Django 5.1.7 on 2025-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0008_openspacebooking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspacebooking',
            name='district',
            field=models.CharField(default='Kinondoni', max_length=250),
        ),
    ]
