# Generated by Django 5.1.7 on 2025-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0010_forwardedbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspacebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
