# Generated by Django 5.1.7 on 2025-05-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0011_openspacebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspacebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
