# Generated by Django 5.1.7 on 2025-06-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapprest', '0012_openspacebooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openspacebooking',
            old_name='date',
            new_name='startdate',
        ),
        migrations.RemoveField(
            model_name='openspacebooking',
            name='duration',
        ),
        migrations.AddField(
            model_name='openspacebooking',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
